---
version: 2
plan:
  project-key: RTP
  key: STPS
  name: Script test plan with specs
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
  - script:
      interpreter: SHELL
      scripts:
      - echo hello
      description: Hello
  artifact-subscriptions: []
repositories: []
# Remove line above if want to set repository with YAML file as primary repository of plan
triggers: []
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: RTP-STP
plan-permissions:
- users:
  - bamboo
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
...
